/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-fixed": "#7ffc97",
        "primary-container": "#7ffc97",
        "on-primary": "#e4ffe2",
        "inverse-primary": "#82ff99",
        "on-tertiary-container": "#466250",
        "on-surface": "#2a3434",
        "error-dim": "#5c1202",
        "outline": "#727d7c",
        "primary-dim": "#006027",
        "inverse-surface": "#0b0f0f",
        "surface-dim": "#cfdddb",
        "on-background": "#2a3434",
        "on-tertiary": "#e7ffec",
        "surface-container-lowest": "#ffffff",
        "secondary": "#5d605b",
        "secondary-container": "#e2e3dd",
        "on-tertiary-fixed-variant": "#506d5a",
        "surface-variant": "#dae5e4",
        "on-primary-fixed-variant": "#006a2c",
        "tertiary": "#496553",
        "surface-container-low": "#f0f4f3",
        "tertiary-container": "#dbfce4",
        "surface-bright": "#f8faf9",
        "surface-container-highest": "#dae5e4",
        "error-container": "#fe8b70",
        "secondary-fixed-dim": "#d4d5cf",
        "on-tertiary-fixed": "#34503e",
        "on-secondary-fixed": "#3d403c",
        "on-surface-variant": "#576160",
        "on-secondary-fixed-variant": "#5a5c58",
        "inverse-on-surface": "#9b9d9d",
        "surface": "#f8faf9",
        "on-secondary-container": "#50524e",
        "tertiary-fixed-dim": "#cdedd6",
        "on-primary-fixed": "#004a1c",
        "secondary-dim": "#515450",
        "on-secondary": "#f8f9f4",
        "surface-container-high": "#e1eae9",
        "secondary-fixed": "#e2e3dd",
        "error": "#9e422c",
        "tertiary-fixed": "#dbfce4",
        "surface-tint": "#006e2d",
        "surface-container": "#e9efee",
        "tertiary-dim": "#3d5948",
        "primary": "#006e2d",
        "outline-variant": "#a9b4b3",
        "primary-fixed-dim": "#70ed8a",
        "on-primary-container": "#005f27",
        "on-error-container": "#742410",
        "on-error": "#fff7f6",
        "background": "#f8faf9"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      fontFamily: {
        "headline": ["Inter", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
